<?php

namespace App\Http\Controllers;

use App\Models\LguUser;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Hash;

class LguUserController extends Controller
{
    /**
     * Display a listing of LGU users.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        try {
            $users = LguUser::all();
            return response()->json([
                'success' => true,
                'data' => $users
            ], 200);
        } catch (\Exception $e) {
            Log::error('Failed to fetch users: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Failed to fetch users: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created LGU user.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        try {
            $validated = $request->validate([
                'name' => 'nullable|string|max:64',
                'first_name' => 'required|string|max:64',
                'last_name' => 'required|string|max:64',
                'role' => 'required|string|max:32',
                'birth_date' => 'required|date',
                'phone_number' => 'required|string|max:15',
                'email' => 'required|email|max:128|unique:lgu_users,email',
                'password' => 'nullable|string|min:6', // Optional, will auto-generate if not provided
            ]);

            // Auto-generate full name if not provided
            if (empty($validated['name'])) {
                $validated['name'] = trim($validated['first_name'] . ' ' . $validated['last_name']);
            }

            $validated['is_first_login'] = true;

            // Create user (password will be auto-generated by Model boot if not provided)
            $user = LguUser::create($validated);
            
            // Get the plain password for email (Model generates and hashes it)
            $defaultPassword = LguUser::getPlainDefaultPassword($user->first_name, $user->birth_date);
            
            // Send welcome email with credentials
            $this->sendWelcomeEmail($user, $defaultPassword);
            
            return response()->json([
                'success' => true,
                'message' => 'LGU user created successfully. Welcome email sent to ' . $user->email,
                'data' => $user
            ], 201);
        } catch (ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $e->errors()
            ], 422);
        } catch (\Exception $e) {
            Log::error('User creation failed: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'User created but failed to send email: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Send welcome email with login credentials
     *
     * @param  LguUser  $user
     * @param  string  $password
     * @return void
     */
    private function sendWelcomeEmail($user, $password)
    {
        try {
            // Only send email if mail is properly configured
            if (config('mail.mailers.smtp.host')) {
                Mail::send('emails.welcome-user', ['user' => $user, 'password' => $password], function($message) use ($user) {
                    $message->to($user->email)
                            ->subject('Welcome to JuanCharge - Your Login Credentials');
                });
            } else {
                // Log the credentials if email is not configured
                Log::info('User created - Email not sent (mail not configured)', [
                    'email' => $user->email,
                    'password' => $password,
                    'name' => $user->name,
                    'role' => $user->role
                ]);
            }
        } catch (\Exception $e) {
            Log::error('Failed to send welcome email to ' . $user->email . ': ' . $e->getMessage());
            // Don't throw - just log the error so user creation still succeeds
        }
    }

    /**
     * Display the specified LGU user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id)
    {
        try {
            $user = LguUser::find($id);

            if (!$user) {
                return response()->json([
                    'success' => false,
                    'message' => 'LGU user not found'
                ], 404);
            }

            return response()->json([
                'success' => true,
                'data' => $user
            ], 200);
        } catch (\Exception $e) {
            Log::error('Failed to fetch user: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Failed to fetch user: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Update the specified LGU user.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        try {
            $user = LguUser::find($id);

            if (!$user) {
                return response()->json([
                    'success' => false,
                    'message' => 'LGU user not found'
                ], 404);
            }

            $validated = $request->validate([
                'name' => 'sometimes|string|max:64',
                'first_name' => 'sometimes|string|max:64',
                'last_name' => 'sometimes|string|max:64',
                'birth_date' => 'sometimes|date',
                'role' => 'sometimes|string|max:32',
                'phone_number' => 'sometimes|string|max:15',
                'email' => 'sometimes|email|max:128|unique:lgu_users,email,' . $id,
                'password' => 'nullable|string|min:6',
            ]);

            // Auto-update full name if first_name or last_name changed
            if (isset($validated['first_name']) || isset($validated['last_name'])) {
                $firstName = $validated['first_name'] ?? $user->first_name;
                $lastName = $validated['last_name'] ?? $user->last_name;
                $validated['name'] = trim($firstName . ' ' . $lastName);
            }

            $user->update($validated);

            return response()->json([
                'success' => true,
                'message' => 'LGU user updated successfully',
                'data' => $user
            ], 200);
        } catch (ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $e->errors()
            ], 422);
        } catch (\Exception $e) {
            Log::error('Failed to update user: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Failed to update user: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified LGU user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        try {
            $user = LguUser::find($id);

            if (!$user) {
                return response()->json([
                    'success' => false,
                    'message' => 'LGU user not found'
                ], 404);
            }

            $user->delete();

            return response()->json([
                'success' => true,
                'message' => 'LGU user deleted successfully'
            ], 200);
        } catch (\Exception $e) {
            Log::error('Failed to delete user: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Failed to delete user: ' . $e->getMessage()
            ], 500);
        }
    }

    public function disableUser($id)
    {
        try {
            $user = LguUser::find($id);

            if (!$user) {
                return response()->json([
                    'success' => false,
                    'message' => 'LGU user not found'
                ], 404);
            }

            $user->status = 'inactive';
            $user->save();

            return response()->json([
                'success' => true,
                'message' => 'LGU user disabled successfully'
            ], 200);
        } catch (\Exception $e) {
            Log::error('Failed to disable user: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Failed to disable user: ' . $e->getMessage()
            ], 500);
        }
    }
}
