<?php

namespace App\Http\Controllers;

use App\Models\PointVoucher;
use App\Models\Kiosk;
use App\Models\PointsTransaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PointVoucherController extends Controller
{
    /**
     * Store a new point voucher (Generated by Kiosk)
     * Kiosk calls this API to get a QR code/token
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'points' => 'required|integer|min:1',
            'kiosk_code' => 'required|string|exists:kiosks,kiosk_code',
            'items' => 'nullable|array', // JSON array of items from Kiosk
        ]);

        try {
            $kiosk = Kiosk::where('kiosk_code', $validated['kiosk_code'])->firstOrFail();

            // Generate unique code for QR
            $code = Str::uuid()->toString();

            // Set expiry (e.g., 24 hours validity for the QR)
            $expiresAt = Carbon::now()->addHours(24);

            $voucher = PointVoucher::create([
                'code' => $code,
                'points' => $validated['points'],
                'kiosk_id' => $kiosk->id,
                'status' => 'pending',
                'expires_at' => $expiresAt,
                'metadata' => ['items' => $request->items],
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Voucher created successfully',
                'data' => [
                    'code' => $voucher->code, // This code will be encoded in the QR
                    'points' => $voucher->points,
                    'expires_at' => $voucher->expires_at->toIso8601String(),
                ]
            ], 201);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to create voucher: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Claim a point voucher (Called by Mobile App)
     * Authenticated User scans QR and calls this API
     */
    public function claim(Request $request)
    {
        $request->validate([
            'code' => 'required|string|exists:point_vouchers,code',
        ]);

        $user = auth()->user();
        if (!$user) {
            return response()->json(['success' => false, 'message' => 'Unauthenticated'], 401);
        }

        DB::beginTransaction();

        try {
            // Lock relevant voucher for update
            $voucher = PointVoucher::where('code', $request->code)->lockForUpdate()->first();

            if (!$voucher) {
                DB::rollBack();
                return response()->json(['success' => false, 'message' => 'Voucher not found'], 404);
            }

            // Validation checks
            if ($voucher->status !== 'pending') {
                DB::rollBack();
                return response()->json([
                    'success' => false,
                    'message' => 'This voucher has already been claimed or is invalid.'
                ], 400);
            }

            if ($voucher->expires_at && Carbon::now()->gt($voucher->expires_at)) {
                $voucher->status = 'expired';
                $voucher->save();
                DB::rollBack(); // Or commit the expired status change, but simpler to just rollback the transaction if strictly check failed

                // Let's actually commit the expired status change so user knows
                $voucher->save();
                DB::commit();

                return response()->json([
                    'success' => false,
                    'message' => 'This voucher has expired.'
                ], 400);
            }

            // Mark as claimed
            $voucher->status = 'claimed';
            $voucher->claimed_by = $user->id;
            $voucher->claimed_at = Carbon::now();
            $voucher->save();

            // Update User Balance
            // Handle points_balance and points_total
            $user->points_balance = ($user->points_balance ?? 0) + $voucher->points;
            $user->points_total = ($user->points_total ?? 0) + $voucher->points;

            // Logic for weight if applicable (extract from metadata if possible)
            $items = $voucher->metadata['items'] ?? [];
            $weight = 0; // Default
            // Iterate over items if structure is known
            // e.g., [{"points": 1, ...}]
            // Just basic support for now.

            $user->save();

            // Create Transaction Record for History
            PointsTransaction::create([
                'user_id' => $user->id,
                'transaction_type' => 'earned',
                'type' => 'recycling', // Or 'voucher_claim'
                'title' => 'Voucher Claimed',
                'points' => $voucher->points,
                'balance_after' => $user->points_balance,
                'status' => 'completed',
                'reference_type' => 'point_voucher',
                'reference_id' => $voucher->id, // If reference_id is string on PointsTransaction model, cast to string if needed. Assuming int ID is fine or convert.
                // Looking at PointsTransaction model or migration...
                'description' => "Claimed voucher from Kiosk " . ($voucher->kiosk ? $voucher->kiosk->kiosk_code : 'Unknown'),
            ]);

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => 'Points claimed successfully!',
                'data' => [
                    'points_earned' => $voucher->points,
                    'new_balance' => $user->points_balance,
                ]
            ]);

        } catch (\Exception $e) {
            DB::rollBack();
            return response()->json([
                'success' => false,
                'message' => 'Failed to claim points: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Sync offline vouchers from Kiosk (Job/Scheduled)
     * Kiosk uploads its local transaction log here.
     */
    public function sync(Request $request)
    {
        $request->validate([
            'kiosk_code' => 'required|string|exists:kiosks,kiosk_code',
            'transactions' => 'required|array',
            'transactions.*.txn_id' => 'required|string',
            'transactions.*.points' => 'required|integer',
            'transactions.*.timestamp' => 'required|integer',
            'transactions.*.signature' => 'required|string',
        ]);

        $kiosk = Kiosk::where('kiosk_code', $request->kiosk_code)->firstOrFail();
        $secret = env('KIOSK_SECRET_KEY', 'default_secret_key'); // Should be secure
        $syncedCount = 0;
        $errors = [];

        foreach ($request->transactions as $txn) {
            // 1. Verify Signature
            // Payload: kiosk_code + txn_id + points + timestamp
            $payload = $request->kiosk_code . $txn['txn_id'] . $txn['points'] . $txn['timestamp'];
            $expectedSignature = hash_hmac('sha256', $payload, $secret);

            if (!hash_equals($expectedSignature, $txn['signature'])) {
                $errors[] = ['txn_id' => $txn['txn_id'], 'error' => 'Invalid signature'];
                continue;
            }

            // 2. Check for Replay (Idempotency)
            if (PointVoucher::where('code', $txn['txn_id'])->exists()) {
                $syncedCount++;
                continue;
            }

            PointVoucher::create([
                'code' => $txn['txn_id'],
                'points' => $txn['points'],
                'kiosk_id' => $kiosk->id,
                'status' => 'pending',
                'expires_at' => Carbon::createFromTimestampMs($txn['timestamp'])->addHours(24),
                'metadata' => ['source' => 'offline_sync', 'timestamp' => $txn['timestamp']],
            ]);

            $syncedCount++;
        }

        return response()->json([
            'success' => true,
            'synced_count' => $syncedCount,
            'errors' => $errors
        ]);
    }

    /**
     * Claim with Signed Payload (For when Kiosk is offline)
     * Mobile scans the QR (which contains signature) and sends it here.
     */
    public function claimSigned(Request $request)
    {
        $request->validate([
            'kiosk_code' => 'required|string|exists:kiosks,kiosk_code',
            'txn_id' => 'required|string',
            'points' => 'required|integer',
            'timestamp' => 'required|integer',
            'signature' => 'required|string',
        ]);

        $user = auth()->user();
        if (!$user)
            return response()->json(['message' => 'Unauthenticated'], 401);

        // Verify Signature
        $secret = env('KIOSK_SECRET_KEY', 'default_secret_key');
        $payload = $request->kiosk_code . $request->txn_id . $request->points . $request->timestamp;
        $expectedSignature = hash_hmac('sha256', $payload, $secret);

        if (!hash_equals($expectedSignature, $request->signature)) {
            return response()->json(['success' => false, 'message' => 'Invalid voucher signature'], 400);
        }

        DB::beginTransaction();
        try {
            // Check if voucher exists
            $voucher = PointVoucher::where('code', $request->txn_id)->lockForUpdate()->first();

            if (!$voucher) {
                // Create it on the fly (it's valid because signature matched)
                $kiosk = Kiosk::where('kiosk_code', $request->kiosk_code)->first();
                $voucher = PointVoucher::create([
                    'code' => $request->txn_id,
                    'points' => $request->points,
                    'kiosk_id' => $kiosk->id,
                    'status' => 'pending',
                    'expires_at' => Carbon::createFromTimestampMs($request->timestamp)->addHours(24),
                    'metadata' => ['source' => 'online_claim_signed', 'timestamp' => $request->timestamp],
                ]);
            }

            if ($voucher->status !== 'pending') {
                DB::rollBack();
                return response()->json(['success' => false, 'message' => 'Voucher already claimed/expired'], 400);
            }

            // Mark claimed and award points
            $voucher->status = 'claimed';
            $voucher->claimed_by = $user->id;
            $voucher->claimed_at = Carbon::now();
            $voucher->save();

            $user->points_balance += $voucher->points;
            $user->points_total += $voucher->points;
            $user->save();

            PointsTransaction::create([
                'user_id' => $user->id,
                'transaction_type' => 'earned',
                'type' => 'recycling',
                'title' => 'Voucher Claimed (Offline Kiosk)',
                'points' => $voucher->points,
                'balance_after' => $user->points_balance,
                'status' => 'completed',
                'reference_type' => 'point_voucher',
                'reference_id' => $voucher->id,
                'description' => "Claimed voucher from Kiosk " . ($voucher->kiosk ? $voucher->kiosk->kiosk_code : 'Unknown'),
            ]);

            DB::commit();

            return response()->json([
                'success' => true,
                'data' => [
                    'points_earned' => $voucher->points,
                    'new_balance' => $user->points_balance
                ]
            ]);

        } catch (\Exception $e) {
            DB::rollBack();
            return response()->json(['success' => false, 'message' => $e->getMessage()], 500);
        }
    }
}
